spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver     # MySQL driver class name
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

